[[envers.configuration]]
= Cấu hình

Để bắt đầu sử dụng Spring Data Envers, bạn cần một project có Spring Data JPA trên classpath và thêm dependency `spring-data-envers`:

====
[source,xml,subs="+attributes"]
----
<dependencies>

  <!-- other dependency elements omitted -->

  <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-envers</artifactId>
    <version>{version}</version>
  </dependency>

</dependencies>
----
====

Việc này cũng sẽ kéo theo `hibernate-envers` vào project như một transient dependency.

Để bật Spring Data Envers và Spring Data JPA, chúng ta cần cấu hình ba bean (`DataSource`, `EntityManagerFactory`, và `PlatformTransactionManager`).
`@EnableEnversRepositories` đã tự động cung cấp sẵn `repositoryFactoryBeanClass`:

====
[source,java]
----
@Configuration
@EnableEnversRepositories
@EnableTransactionManagement
public class EnversDemoConfiguration {

	@Bean
	public DataSource dataSource() {

		EmbeddedDatabaseBuilder builder = new EmbeddedDatabaseBuilder();
		return builder.setType(EmbeddedDatabaseType.HSQL).build();
	}

	@Bean
	public LocalContainerEntityManagerFactoryBean entityManagerFactory() {

		HibernateJpaVendorAdapter vendorAdapter = new HibernateJpaVendorAdapter();
		vendorAdapter.setGenerateDdl(true);

		LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
		factory.setJpaVendorAdapter(vendorAdapter);
		factory.setPackagesToScan("example.springdata.jpa.envers");
		factory.setDataSource(dataSource());
		return factory;
	}

	@Bean
	public PlatformTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {

		JpaTransactionManager txManager = new JpaTransactionManager();
		txManager.setEntityManagerFactory(entityManagerFactory);
		return txManager;
	}
}
----
====

Để thực sự sử dụng Spring Data Envers, hãy biến một hoặc nhiều repository thành {spring-data-commons-javadoc-base}/org/springframework/data/repository/history/RevisionRepository.html[`RevisionRepository`] bằng cách thêm nó vào như một extended interface:

====
[source,java]
----
interface PersonRepository
    extends CrudRepository<Person, Long>,
    RevisionRepository<Person, Long, Long> // <1>
{}
----
<1> Type parameter đầu tiên (`Person`) biểu thị entity type, type parameter thứ hai (`Long`) biểu thị type của id property, và type parameter cuối cùng (`Long`) là type của revision number.
Đối với Envers ở cấu hình mặc định, tham số revision number nên là `Integer` hoặc `Long`.
====

Entity của repository đó phải là một entity đã bật Envers auditing (tức là phải có annotation `@Audited`):

====
[source,java]
----
@Entity
@Audited
class Person {

	@Id @GeneratedValue
	Long id;
	String name;
	@Version Long version;
}
----
====
