[[envers.usage]]
= Sử dụng

Giờ đây bạn có thể sử dụng các method từ `RevisionRepository` để query các revision của entity, như test case sau đây cho thấy:

====
[source,java]
----
@ExtendWith(SpringExtension.class)
@Import(EnversDemoConfiguration.class) // <1>
class EnversIntegrationTests {

	final PersonRepository repository;
	final TransactionTemplate tx;

	EnversIntegrationTests(@Autowired PersonRepository repository, @Autowired PlatformTransactionManager tm) {
		this.repository = repository;
		this.tx = new TransactionTemplate(tm);
	}

	@Test
	void testRepository() {

		Person updated = preparePersonHistory();

		Revisions<Long, Person> revisions = repository.findRevisions(updated.id);

		Iterator<Revision<Long, Person>> revisionIterator = revisions.iterator();

		checkNextRevision(revisionIterator, "John", RevisionType.INSERT);
		checkNextRevision(revisionIterator, "Jonny", RevisionType.UPDATE);
		checkNextRevision(revisionIterator, null, RevisionType.DELETE);
		assertThat(revisionIterator.hasNext()).isFalse();

	}

	/**
    * Kiểm tra rằng phần tử tiếp theo trong iterator là một Revision entry tham chiếu đến một Person
    * có name được cung cấp, sau thay đổi đã tạo ra Revision đó.
    * <p>
    * Một side effect là Iterator được advance thêm một phần tử.
    *
    * @param revisionIterator iterator cần được test.
    * @param name name mong đợi của Person được Revision tham chiếu.
    * @param revisionType type của revision, cho biết revision đó đại diện cho insert, update hay delete.
    */
	private void checkNextRevision(Iterator<Revision<Long, Person>> revisionIterator, String name,
			RevisionType revisionType) {

		assertThat(revisionIterator.hasNext()).isTrue();
		Revision<Long, Person> revision = revisionIterator.next();
		assertThat(revision.getEntity().name).isEqualTo(name);
		assertThat(revision.getMetadata().getRevisionType()).isEqualTo(revisionType);
	}

	/**
    * Tạo một Person với một vài thay đổi để có revision history không đơn giản.
    * @return Person được tạo.
    */
	private Person preparePersonHistory() {

		Person john = new Person();
		john.setName("John");

		// tạo
		Person saved = tx.execute(__ -> repository.save(john));
		assertThat(saved).isNotNull();

		saved.setName("Jonny");

		// cập nhật
		Person updated = tx.execute(__ -> repository.save(saved));
		assertThat(updated).isNotNull();

		// xóa
		tx.executeWithoutResult(__ -> repository.delete(updated));
		return updated;
	}
}
----
<1> Dòng này tham chiếu đến cấu hình application context được trình bày trước đó (trong phần xref:envers/configuration.adoc#envers.configuration[Cấu hình]).
====

[[envers.resources]]
== Tài nguyên bổ sung

Bạn có thể tải https://github.com/spring-projects/spring-data-examples[ví dụ Spring Data Envers trong repository Spring Data Examples] và thử nghiệm để hiểu rõ hơn cách thư viện hoạt động.

Bạn cũng nên tham khảo {spring-data-commons-javadoc-base}/org/springframework/data/repository/history/RevisionRepository.html[Javadoc của `RevisionRepository`] và các class liên quan.

Bạn có thể đặt câu hỏi tại https://stackoverflow.com/questions/tagged/spring-data-envers[Stackoverflow bằng cách sử dụng tag `spring-data-envers`].

https://github.com/spring-projects/spring-data-jpa[Source code và issue tracker của Spring Data Envers được lưu trữ tại GitHub] (như một module của Spring Data JPA).
