[[envers.usage]]
= Sử dụng

Giờ đây bạn có thể sử dụng các method của `RevisionRepository` để truy vấn các revision của entity, như test case sau đây minh họa:

====
[source,java]
----
@ExtendWith(SpringExtension.class)
@Import(EnversDemoConfiguration.class) // <1>
class EnversIntegrationTests {

	final PersonRepository repository;
	final TransactionTemplate tx;

	EnversIntegrationTests(@Autowired PersonRepository repository, @Autowired PlatformTransactionManager tm) {
		this.repository = repository;
		this.tx = new TransactionTemplate(tm);
	}

	@Test
	void testRepository() {

		Person updated = preparePersonHistory();

		Revisions<Long, Person> revisions = repository.findRevisions(updated.id);

		Iterator<Revision<Long, Person>> revisionIterator = revisions.iterator();

		checkNextRevision(revisionIterator, "John", RevisionType.INSERT);
		checkNextRevision(revisionIterator, "Jonny", RevisionType.UPDATE);
		checkNextRevision(revisionIterator, null, RevisionType.DELETE);
		assertThat(revisionIterator.hasNext()).isFalse();

	}

	/**
    * Checks that the next element in the iterator is a Revision entry referencing a Person
    * with the given name after whatever change brought that Revision into existence.
    * <p>
    * As a side effect the Iterator gets advanced by one element.
    *
    * @param revisionIterator the iterator to be tested.
    * @param name the expected name of the Person referenced by the Revision.
    * @param revisionType the type of the revision denoting if it represents an insert, update or delete.
    */
	private void checkNextRevision(Iterator<Revision<Long, Person>> revisionIterator, String name,
			RevisionType revisionType) {

		assertThat(revisionIterator.hasNext()).isTrue();
		Revision<Long, Person> revision = revisionIterator.next();
		assertThat(revision.getEntity().name).isEqualTo(name);
		assertThat(revision.getMetadata().getRevisionType()).isEqualTo(revisionType);
	}

	/**
    * Creates a Person with a couple of changes so it has a non-trivial revision history.
    * @return the created Person.
    */
	private Person preparePersonHistory() {

		Person john = new Person();
		john.setName("John");

		// create
		Person saved = tx.execute(__ -> repository.save(john));
		assertThat(saved).isNotNull();

		saved.setName("Jonny");

		// update
		Person updated = tx.execute(__ -> repository.save(saved));
		assertThat(updated).isNotNull();

		// delete
		tx.executeWithoutResult(__ -> repository.delete(updated));
		return updated;
	}
}
----
<1> Dòng này tham chiếu đến cấu hình application context đã trình bày trước đó (trong phần xref:envers/configuration.adoc#envers.configuration[Cấu hình]).
====

[[envers.resources]]
== Tài nguyên bổ sung

Bạn có thể tải https://github.com/spring-projects/spring-data-examples[ví dụ Spring Data Envers trong repository Spring Data Examples] về và thử nghiệm để có cảm nhận về cách thư viện này hoạt động.

Bạn cũng nên tham khảo {spring-data-commons-javadoc-base}/org/springframework/data/repository/history/RevisionRepository.html[Javadoc của `RevisionRepository`] và các class liên quan.

Bạn có thể đặt câu hỏi tại https://stackoverflow.com/questions/tagged/spring-data-envers[Stackoverflow bằng cách sử dụng tag `spring-data-envers`].

https://github.com/spring-projects/spring-data-jpa[Source code và issue tracker của Spring Data Envers được lưu trữ tại GitHub] (như một module của Spring Data JPA).
