include::{commons}@data-commons-vi::page$aot.adoc[]

[[aot.repositories.jpa]]
== JPA Repository Ahead of Time

Các AOT repository lọc các method đủ điều kiện cho AOT processing.
Thông thường, đây là toàn bộ query method không có một xref:repositories/custom-implementations.adoc[implementation fragment] hỗ trợ.

[NOTE]
====
AOT processing không truy cập database.
Vì vậy, nó khởi tạo một Hibernate instance in-memory để thu thập metadata.
Các type dùng cho Hibernate configuration được xác định bởi AOT metadata collector của chúng tôi.
Chúng tôi ưu tiên sử dụng một `PersistenceManagedTypes` bean nếu có sẵn, và fallback về `PersistenceUnitInfo` hoặc các type do chúng tôi tự discover.
Nếu type scanning của chúng tôi không đủ cho setup của bạn, bạn có thể bật việc sử dụng trực tiếp `EntityManagerFactory` bằng cách cấu hình property `spring.aot.jpa.repositories.use-entitymanager=true`.
====

**Các feature được hỗ trợ**

* Derived query method, `@Query`/`@NativeQuery` và named query method
* Stored procedure query method được annotate bằng `@Procedure`
* Các method có `@Modifying` và trả về `void` hoặc `int`
* Hỗ trợ `@QueryHints`
* Các return type Pagination, `Slice`, `Stream`, và `Optional`
* Sort query rewriting
* Interface projection và DTO projection
* Value Expressions (Các expression này cần một số reflective information.
Lưu ý rằng việc sử dụng Value Expression yêu cầu expression parsing và contextual information để evaluate expression)

**Các giới hạn**

* Yêu cầu Hibernate cho AOT processing.
* `QueryRewriter` phải là một class không có tham số (no-args). Các `QueryRewriter` bean hiện chưa được hỗ trợ.
* Các method nhận `ScrollPosition` (ví dụ: `Keyset` pagination) hiện chưa được hỗ trợ.
* Các custom Collection return type (ví dụ: `io.vavr.collection`, `org.eclipse.collections`) hiện chưa được hỗ trợ.

**Các method bị loại trừ**

* `CrudRepository`, Querydsl, Query by Example, và các method khác của base interface vì implementation của chúng được cung cấp bởi base class hoặc các fragment tương ứng
* Các method có implementation quá phức tạp
** Các method nhận `ScrollPosition` (ví dụ: `Keyset` pagination)
** Dynamic projections
