[appendix]
[[faq]]
= Câu hỏi thường gặp

[[faq.common]]
== Chung

[qanda]
Tôi muốn có thông tin logging chi tiết hơn về những method nào được gọi bên trong `JpaRepository`, chẳng hạn. Làm thế nào để có được thông tin này? :: Bạn có thể sử dụng `CustomizableTraceInterceptor` do Spring cung cấp, như trong ví dụ sau:
+
[source, xml]
----
<bean id="customizableTraceInterceptor" class="
  org.springframework.aop.interceptor.CustomizableTraceInterceptor">
  <property name="enterMessage" value="Entering $[methodName]($[arguments])"/>
  <property name="exitMessage" value="Leaving $[methodName](): $[returnValue]"/>
</bean>

<aop:config>
  <aop:advisor advice-ref="customizableTraceInterceptor"
    pointcut="execution(public * org.springframework.data.jpa.repository.JpaRepository+.*(..))"/>
</aop:config>
----

[[faq.auditing]]
== Auditing

[qanda]
Tôi muốn sử dụng khả năng auditing của Spring Data JPA nhưng database của tôi đã được cấu hình sẵn để tự set modification date và creation date trên entity. Làm sao để ngăn Spring Data tự set date theo cách lập trình? :: Set attribute `set-dates` của namespace element `auditing` thành `false`.


[[faq.hibernate]]
== Hibernate

[qanda]
Tôi có thể dùng Hibernate 8 với Spring Data JPA không? :: Spring Data JPA hiện đang phụ thuộc vào JPA 3.2 và Hibernate 7, nhưng cung cấp hỗ trợ best-effort cho các preview release của Hibernate 8 (Beta1) và Jakarta Persistence 4.0 (M5).
