[[jpa.getting-started]]
= Bắt đầu

Một cách dễ dàng để khởi tạo một môi trường làm việc là tạo một project dựa trên Spring thông qua https://start.spring.io/#!type=maven-project&dependencies=h2,data-jpa[start.spring.io] hoặc tạo một Spring project trong https://spring.io/tools[Spring Tools].

[[jpa.examples-repo]]
== Repository chứa các ví dụ

Repository https://github.com/spring-projects/spring-data-examples[spring-data-examples] trên GitHub chứa một số ví dụ mà bạn có thể tải xuống và thử nghiệm để hình dung cách library này hoạt động.

[[jpa.hello-world]]
== Hello World

Hãy bắt đầu với một entity đơn giản và repository tương ứng của nó:

[source,java]
----
@Entity
class Person {

  @Id @GeneratedValue(strategy = GenerationType.AUTO)
  private Long id;
  private String name;

  // getters and setters omitted for brevity
}

interface PersonRepository extends Repository<Person, Long> {

  Person save(Person person);

  Optional<Person> findById(long id);
}
----

Tạo application chính để chạy ứng dụng, như trong ví dụ sau:

[source,java]
----
@SpringBootApplication
public class DemoApplication {

  public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
  }

  @Bean
  CommandLineRunner runner(PersonRepository repository) {
    return args -> {

      Person person = new Person();
      person.setName("John");

      repository.save(person);
      Person saved = repository.findById(person.getId()).orElseThrow(NoSuchElementException::new);
    };
  }
}
----

Ngay cả trong ví dụ đơn giản này, cũng có một vài điểm đáng chú ý:

* Các repository instance được tự động implement.
Khi được dùng làm parameter của các method có `@Bean`, các instance này sẽ được autowired mà không cần thêm annotation nào khác.
* Repository cơ bản kế thừa `Repository`.
Chúng tôi khuyến nghị bạn cân nhắc mức API surface muốn expose cho ứng dụng của mình.
Các repository interface phức tạp hơn gồm `ListCrudRepository` hoặc `JpaRepository`.
