[[jpa.getting-started]]
= Bắt đầu

Một cách đơn giản để bootstrap việc thiết lập một working environment là tạo một Spring-based project thông qua https://start.spring.io/#!type=maven-project&dependencies=h2,data-jpa[start.spring.io] hoặc tạo một Spring project trong https://spring.io/tools[Spring Tools].

[[jpa.examples-repo]]
== Repository Ví dụ

GitHub https://github.com/spring-projects/spring-data-examples[spring-data-examples repository] chứa nhiều ví dụ mà bạn có thể tải về và thử nghiệm để cảm nhận cách library này hoạt động.

[[jpa.hello-world]]
== Hello World

Hãy bắt đầu với một entity đơn giản và repository tương ứng của nó:

[source,java]
----
@Entity
class Person {

  @Id @GeneratedValue(strategy = GenerationType.AUTO)
  private Long id;
  private String name;

  // getters and setters omitted for brevity
}

interface PersonRepository extends Repository<Person, Long> {

  Person save(Person person);

  Optional<Person> findById(long id);
}
----

Tạo main application để chạy, như ví dụ sau đây:

[source,java]
----
@SpringBootApplication
public class DemoApplication {

  public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
  }

  @Bean
  CommandLineRunner runner(PersonRepository repository) {
    return args -> {

      Person person = new Person();
      person.setName("John");

      repository.save(person);
      Person saved = repository.findById(person.getId()).orElseThrow(NoSuchElementException::new);
    };
  }
}
----

Ngay cả trong ví dụ đơn giản này, cũng có một vài điểm đáng chú ý:

* Các repository instance được tự động implement.
Khi được dùng làm parameter của các `@Bean` method, chúng sẽ được autowired mà không cần thêm annotation nào khác.
* Repository cơ bản extends `Repository`.
Chúng tôi đề xuất bạn cân nhắc muốn expose bao nhiêu API surface cho ứng dụng của mình.
Các repository interface phức tạp hơn là `ListCrudRepository` hoặc `JpaRepository`.
