[glossary]
[[glossary]]
= Glossary
:page-section-summary-toc: 1

AOP :: Lập trình hướng khía cạnh (Aspect Oriented Programming)

Commons DBCP :: Commons DataBase Connection Pools - một thư viện của Apache Foundation cung cấp các pooling implementation của interface DataSource.

CRUD :: Create, Read, Update, Delete - Các thao tác persistence cơ bản.

DAO :: Data Access Object - Pattern giúp tách biệt persisting logic khỏi object cần được persist

Dependency Injection :: Pattern truyền dependency của một component cho component đó từ bên ngoài, giúp component không cần tự đi lookup dependency của mình. Để biết thêm thông tin, xem link:$$https://en.wikipedia.org/wiki/Dependency_Injection$$[https://en.wikipedia.org/wiki/Dependency_Injection].

EclipseLink :: Object relational mapper triển khai JPA - link:$$https://www.eclipse.org/eclipselink/$$[https://www.eclipse.org/eclipselink/]

Hibernate :: Object relational mapper triển khai JPA - link:$$https://hibernate.org/$$[https://hibernate.org/]

JPA :: Jakarta Persistence API

Spring :: Framework ứng dụng Java - link:$$https://spring.io/projects/spring-framework/$$[https://spring.io/projects/spring-framework]
