[[jpd.misc.cdi-integration]]
= Tích hợp CDI

Các instance của repository interface thường được tạo bởi một container; khi làm việc với Spring Data, Spring là lựa chọn tự nhiên nhất. Spring cung cấp hỗ trợ chuyên sâu cho việc tạo bean instance, như được mô tả trong {spring-data-commons-docs-url}/repositories/create-instances.html[Tạo instance cho repository]. Kể từ version 1.1.0, Spring Data JPA đi kèm một CDI extension tùy chỉnh cho phép sử dụng repository abstraction trong môi trường CDI. Extension này nằm trong JAR. Để kích hoạt extension, hãy thêm JAR của Spring Data JPA vào classpath.

Bạn có thể thiết lập infrastructure bằng cách triển khai một CDI Producer cho `EntityManagerFactory` và `EntityManager`, như trong ví dụ sau:

[source, java]
----
class EntityManagerFactoryProducer {

  @Produces
  @ApplicationScoped
  public EntityManagerFactory createEntityManagerFactory() {
    return Persistence.createEntityManagerFactory("my-persistence-unit");
  }

  public void close(@Disposes EntityManagerFactory entityManagerFactory) {
    entityManagerFactory.close();
  }

  @Produces
  @RequestScoped
  public EntityManager createEntityManager(EntityManagerFactory entityManagerFactory) {
    return entityManagerFactory.createEntityManager();
  }

  public void close(@Disposes EntityManager entityManager) {
    entityManager.close();
  }
}
----

Thiết lập cần thiết có thể khác nhau tùy theo môi trường JavaEE. Bạn có thể chỉ cần khai báo lại một `EntityManager` dưới dạng CDI bean, như sau:

[source, java]
----
class CdiConfig {

  @Produces
  @RequestScoped
  @PersistenceContext
  public EntityManager entityManager;
}
----

Trong ví dụ trên, container phải có khả năng tự tạo các `EntityManager` của JPA. Toàn bộ cấu hình chỉ re-export `EntityManager` của JPA dưới dạng CDI bean.

Spring Data JPA CDI extension sẽ nhận diện tất cả các instance `EntityManager` khả dụng dưới dạng CDI bean và tạo một proxy cho Spring Data repository bất cứ khi nào container yêu cầu một bean thuộc kiểu repository. Do đó, để lấy một instance của Spring Data repository, bạn chỉ cần khai báo một property có `@Inject`, như trong ví dụ sau:

[source, java]
----
class RepositoryClient {

  @Inject
  PersonRepository repository;

  public void businessMethod() {
    List<Person> people = repository.findAll();
  }
}
----
