[[jpd.misc.cdi-integration]]
= Tích hợp CDI

Instance của các repository interface thường được tạo bởi một container, và Spring là lựa chọn tự nhiên nhất khi làm việc với Spring Data. Spring cung cấp hỗ trợ tinh vi cho việc tạo bean instance, như đã trình bày tại {spring-data-commons-docs-url}/repositories/create-instances.html[Creating Repository Instances]. Kể từ phiên bản 1.1.0, Spring Data JPA đi kèm một CDI extension tùy chỉnh cho phép sử dụng repository abstraction trong các môi trường CDI. Extension này là một phần của JAR. Để kích hoạt nó, chỉ cần thêm JAR của Spring Data JPA vào classpath của bạn.

Giờ đây bạn có thể thiết lập infrastructure bằng cách triển khai một CDI Producer cho `EntityManagerFactory` và `EntityManager`, như trong ví dụ sau:

[source, java]
----
class EntityManagerFactoryProducer {

  @Produces
  @ApplicationScoped
  public EntityManagerFactory createEntityManagerFactory() {
    return Persistence.createEntityManagerFactory("my-persistence-unit");
  }

  public void close(@Disposes EntityManagerFactory entityManagerFactory) {
    entityManagerFactory.close();
  }

  @Produces
  @RequestScoped
  public EntityManager createEntityManager(EntityManagerFactory entityManagerFactory) {
    return entityManagerFactory.createEntityManager();
  }

  public void close(@Disposes EntityManager entityManager) {
    entityManager.close();
  }
}
----

Việc setup cần thiết có thể khác nhau tùy theo môi trường JavaEE. Bạn có thể không cần làm gì thêm ngoài việc khai báo lại một `EntityManager` như một CDI bean, như sau:

[source, java]
----
class CdiConfig {

  @Produces
  @RequestScoped
  @PersistenceContext
  public EntityManager entityManager;
}
----

Trong ví dụ trên, container phải có khả năng tự tạo ra các `EntityManager` của JPA. Toàn bộ đoạn cấu hình chỉ làm một việc là re-export `EntityManager` của JPA thành một CDI bean.

Spring Data JPA CDI extension sẽ nhận diện tất cả các instance `EntityManager` khả dụng như các CDI bean, và tạo một proxy cho một Spring Data repository bất cứ khi nào container yêu cầu một bean thuộc kiểu repository. Do đó, để lấy được một instance của Spring Data repository, bạn chỉ cần khai báo một property với `@Inject`, như trong ví dụ sau:

[source, java]
----
class RepositoryClient {

  @Inject
  PersonRepository repository;

  public void businessMethod() {
    List<Person> people = repository.findAll();
  }
}
----
