[[jpa.misc.merging-persistence-units]]
= Merging persistence units

Spring hỗ trợ việc có nhiều persistence unit. Tuy nhiên, đôi khi bạn có thể muốn modularize ứng dụng của mình nhưng vẫn đảm bảo tất cả các module này chạy bên trong một persistence unit duy nhất. Để bật hành vi đó, Spring Data JPA cung cấp một implementation của `PersistenceUnitManager` tự động merge các persistence unit dựa trên tên của chúng, như ví dụ sau:

.Sử dụng MergingPersistenceUnitManager
====
[source, xml]
----
<bean class="….LocalContainerEntityManagerFactoryBean">
  <property name="persistenceUnitManager">
    <bean class="….MergingPersistenceUnitManager" />
  </property>
</bean>
----
====

[[jpa.misc.entity-scanning]]
== Classpath Scanning cho các Entity Class có @Entity và JPA Mapping File

Một thiết lập JPA thông thường yêu cầu tất cả các annotation-mapped entity class phải được liệt kê trong `orm.xml`. Điều tương tự cũng áp dụng cho các XML mapping file. Spring Data JPA cung cấp một `ClasspathScanningPersistenceUnitPostProcessor` nhận vào một base package đã cấu hình và tùy chọn nhận thêm một mapping filename pattern. Sau đó, nó sẽ scan package đã cho để tìm các class được đánh dấu bằng `@Entity` hoặc `@MappedSuperclass`, load các configuration file khớp với filename pattern, rồi đưa chúng vào JPA configuration. Post-processor này phải được cấu hình như sau:

.Sử dụng ClasspathScanningPersistenceUnitPostProcessor
====
[source, xml]
----
<bean class="….LocalContainerEntityManagerFactoryBean">
  <property name="persistenceUnitPostProcessors">
    <list>
      <bean class="org.springframework.data.jpa.support.ClasspathScanningPersistenceUnitPostProcessor">
        <constructor-arg value="com.acme.domain" />
        <property name="mappingFileNamePattern" value="**/*Mapping.xml" />
      </bean>
    </list>
  </property>
</bean>
----
====

NOTE: Kể từ Spring 3.1, một package cần scan có thể được cấu hình trực tiếp trên `LocalContainerEntityManagerFactoryBean` để bật classpath scanning cho entity class. Xem link:{springJavadocUrl}/org/springframework/orm/jpa/LocalContainerEntityManagerFactoryBean.html#setPackagesToScan(java.lang.String...)$$[JavaDoc] để biết chi tiết.

