[[jpa.misc.merging-persistence-units]]
= Merge các persistence unit

Spring hỗ trợ việc sử dụng nhiều persistence unit. Tuy nhiên, đôi khi bạn có thể muốn module hóa ứng dụng nhưng vẫn đảm bảo tất cả module chạy trong cùng một persistence unit. Để bật hành vi này, Spring Data JPA cung cấp một implementation của `PersistenceUnitManager` tự động merge các persistence unit dựa trên tên của chúng, như trong ví dụ sau:

.Sử dụng MergingPersistenceUnitManager
====
[source, xml]
----
<bean class="….LocalContainerEntityManagerFactoryBean">
  <property name="persistenceUnitManager">
    <bean class="….MergingPersistenceUnitManager" />
  </property>
</bean>
----
====

[[jpa.misc.entity-scanning]]
== Classpath Scanning cho các entity class có @Entity và JPA mapping file

Một thiết lập JPA thuần yêu cầu tất cả entity class được mapping bằng annotation phải được liệt kê trong `orm.xml`. Điều tương tự cũng áp dụng cho các XML mapping file. Spring Data JPA cung cấp một `ClasspathScanningPersistenceUnitPostProcessor` nhận một base package được cấu hình và tùy chọn nhận một mapping filename pattern. Sau đó, nó scan package đã cho để tìm các class có annotation `@Entity` hoặc `@MappedSuperclass`, load các configuration file khớp với filename pattern rồi đưa chúng vào JPA configuration. Post-processor này phải được cấu hình như sau:

.Sử dụng ClasspathScanningPersistenceUnitPostProcessor
====
[source, xml]
----
<bean class="….LocalContainerEntityManagerFactoryBean">
  <property name="persistenceUnitPostProcessors">
    <list>
      <bean class="org.springframework.data.jpa.support.ClasspathScanningPersistenceUnitPostProcessor">
        <constructor-arg value="com.acme.domain" />
        <property name="mappingFileNamePattern" value="**/*Mapping.xml" />
      </bean>
    </list>
  </property>
</bean>
----
====

NOTE: Kể từ Spring 3.1, có thể cấu hình trực tiếp package cần scan trên `LocalContainerEntityManagerFactoryBean` để bật classpath scanning cho entity class. Xem link:{springJavadocUrl}/org/springframework/orm/jpa/LocalContainerEntityManagerFactoryBean.html#setPackagesToScan(java.lang.String...)$$[JavaDoc] để biết chi tiết.
