[[jpa.stored-procedures]]
= Stored Procedures

Đặc tả JPA 2.1 giới thiệu khả năng gọi stored procedure thông qua API `StoredProcedureQuery`.
Chúng tôi đã giới thiệu annotation `@Procedure` để khai báo metadata của stored procedure trên một repository method.

Các ví dụ dưới đây sử dụng stored procedure sau:

.Định nghĩa procedure `plus1inout` trong HSQL DB.
====
[source, sql]
----
/;
DROP procedure IF EXISTS plus1inout
/;
CREATE procedure plus1inout (IN arg int, OUT res int)
BEGIN ATOMIC
 set res = arg + 1;
END
/;
----
====

Metadata của stored procedure có thể được cấu hình bằng annotation `@NamedStoredProcedureQuery` trên một entity type.

[[jpa.stored-procedure-entity-metadata]]
.Định nghĩa metadata của StoredProcedure trên một entity.
====
[source, java]
----
@Entity
@NamedStoredProcedureQuery(name = "User.plus1", procedureName = "plus1inout", parameters = {
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "arg", type = Integer.class),
  @StoredProcedureParameter(mode = ParameterMode.OUT, name = "res", type = Integer.class) })
public class User {}
----
====

Lưu ý rằng `@NamedStoredProcedureQuery` có hai tên khác nhau cho stored procedure.
`name` là tên mà JPA sử dụng. `procedureName` là tên của stored procedure trong database.

Bạn có thể tham chiếu stored procedure từ một repository method theo nhiều cách.
Stored procedure cần gọi có thể được định nghĩa trực tiếp bằng attribute `value` hoặc `procedureName` của annotation `@Procedure`.
Cách này tham chiếu trực tiếp đến stored procedure trong database và bỏ qua mọi cấu hình thông qua `@NamedStoredProcedureQuery`.

Ngoài ra, bạn có thể chỉ định attribute `@NamedStoredProcedureQuery.name` làm attribute `@Procedure.name`.
Nếu không có `value`, `procedureName` hay `name` nào được cấu hình, tên của repository method sẽ được dùng làm attribute `name`.

Ví dụ sau minh họa cách tham chiếu đến một procedure được mapping tường minh:

[[jpa.stored-procedure-reference]]
.Tham chiếu procedure được mapping tường minh với tên "plus1inout" trong database.
====
[source, java]
----
@Procedure("plus1inout")
Integer explicitlyNamedPlus1inout(Integer arg);
----
====

Ví dụ sau tương đương với ví dụ trước nhưng dùng alias `procedureName`:

.Tham chiếu procedure được mapping ngầm định với tên "plus1inout" trong database qua alias `procedureName`.
====
[source, java]
----
@Procedure(procedureName = "plus1inout")
Integer callPlus1InOut(Integer arg);
----
====

Ví dụ sau cũng tương đương với hai ví dụ trước nhưng dùng tên method thay cho một annotation attribute được chỉ định tường minh.

.Tham chiếu named stored procedure "User.plus1", được mapping ngầm định trong `EntityManager`, bằng cách dùng tên method.
====
[source, java]
----
@Procedure
Integer plus1inout(@Param("arg") Integer arg);
----
====

Ví dụ sau minh họa cách tham chiếu đến một stored procedure bằng cách tham chiếu attribute `@NamedStoredProcedureQuery.name`.

.Tham chiếu named stored procedure "User.plus1", được mapping tường minh trong `EntityManager`.
====
[source, java]
----
@Procedure(name = "User.plus1")
Integer entityAnnotatedCustomNamedProcedurePlus1(@Param("arg") Integer arg);
----
====

Nếu stored procedure được gọi chỉ có một out parameter, parameter đó có thể được trả về làm giá trị của method.
Nếu có nhiều out parameter được chỉ định trong annotation `@NamedStoredProcedureQuery`, các parameter đó có thể được trả về dưới dạng `Map` với key là tên parameter được đặt trong annotation `@NamedStoredProcedureQuery`.

NOTE: Lưu ý rằng nếu stored procedure trả về một `ResultSet` thì mọi `OUT` parameter sẽ bị bỏ qua, vì Java chỉ có thể trả về một giá trị duy nhất từ method, trừ khi method khai báo kiểu trả về là `Map`.

Ví dụ sau minh họa cách lấy nhiều `OUT` parameter nếu stored procedure có nhiều `OUT` parameter và được đăng ký dưới dạng `@NamedStoredProcedureQuery`. Việc đăng ký `@NamedStoredProcedureQuery` là bắt buộc để cung cấp metadata của parameter.

.Định nghĩa metadata của StoredProcedure trên một entity.
====
[source,java]
----
@Entity
@NamedStoredProcedureQuery(name = "User.multiple_out_parameters", procedureName = "multiple_out_parameters", parameters = {
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "arg", type = Integer.class),
  @StoredProcedureParameter(mode = ParameterMode.REF_CURSOR, name = "some_cursor", type = void.class),
  @StoredProcedureParameter(mode = ParameterMode.OUT, name = "res", type = Integer.class) })
public class User {}
----
====

.Trả về nhiều OUT parameter
====
[source,java]
----
@Procedure(name = "User.multiple_out_parameters")
Map<String, Object> returnsMultipleOutParameters(@Param("arg") Integer arg);
----
====
