include::{commons}@data-commons-vi::page$auditing.adoc[]

Ngoài ra còn có một base class tiện ích, `AbstractAuditable`, mà bạn có thể mở rộng để không phải tự triển khai các method của interface. Tuy nhiên, việc này làm tăng coupling giữa domain class của bạn với Spring Data, và có thể là điều bạn muốn tránh. Thông thường, cách định nghĩa metadata auditing dựa trên annotation được ưu tiên vì ít can thiệp hơn và linh hoạt hơn.


[[jpa.auditing.configuration]]
== Cấu hình Auditing tổng quát

Spring Data JPA đi kèm một entity listener có thể được dùng để kích hoạt việc thu thập thông tin auditing. Trước tiên, bạn phải đăng ký `AuditingEntityListener` để sử dụng cho tất cả entity trong các persistence context của mình trong file `orm.xml`, như ví dụ sau:

.Cấu hình Auditing bằng orm.xml
====
[source, xml]
----
<persistence-unit-metadata>
  <persistence-unit-defaults>
    <entity-listeners>
      <entity-listener class="….data.jpa.domain.support.AuditingEntityListener" />
    </entity-listeners>
  </persistence-unit-defaults>
</persistence-unit-metadata>
----
====

Bạn cũng có thể bật `AuditingEntityListener` trên từng entity bằng annotation `@EntityListeners`, như sau:

====
[source, java]
----
@Entity
@EntityListeners(AuditingEntityListener.class)
public class MyEntity {

}
----
====

NOTE: Tính năng auditing yêu cầu `spring-aspects.jar` phải có mặt trên classpath.

Sau khi đã chỉnh sửa `orm.xml` phù hợp và có `spring-aspects.jar` trên classpath, để kích hoạt auditing, bạn chỉ cần thêm element namespace `auditing` của Spring Data JPA vào configuration của mình, như sau:

.Kích hoạt Auditing bằng cấu hình XML
====
[source, xml]
----
<jpa:auditing auditor-aware-ref="yourAuditorAwareBean" />
----
====

Kể từ Spring Data JPA 1.5, bạn có thể bật auditing bằng cách gắn annotation `@EnableJpaAuditing` vào một configuration class. Bạn vẫn phải chỉnh sửa file `orm.xml` và có `spring-aspects.jar` trên classpath. Ví dụ sau minh họa cách dùng annotation `@EnableJpaAuditing`:

.Kích hoạt Auditing bằng cấu hình Java
====
[source, java]
----
@Configuration
@EnableJpaAuditing
class Config {

  @Bean
  public AuditorAware<AuditableUser> auditorProvider() {
    return new AuditorAwareImpl();
  }
}
----
====

Nếu bạn expose một bean kiểu `AuditorAware` cho `ApplicationContext`, infrastructure auditing sẽ tự động nhận diện và sử dụng bean đó để xác định người dùng hiện tại cần được set trên domain type. Nếu có nhiều implementation được đăng ký trong `ApplicationContext`, bạn có thể chọn implementation sẽ được sử dụng bằng cách thiết lập tường minh attribute `auditorAwareRef` của `@EnableJpaAuditing`.

// FIXME: phần này có cần tồn tại không?
// [[jpa.misc]]
// = Các lưu ý khác
