include::{commons}@data-commons::page$auditing.adoc[]

Ngoài ra còn có một convenience base class, `AbstractAuditable`, mà bạn có thể extend để tránh phải tự implement thủ công các interface method. Tuy nhiên, làm vậy sẽ làm tăng sự coupling giữa domain class của bạn với Spring Data, điều mà bạn có thể muốn tránh. Thông thường, cách định nghĩa auditing metadata bằng annotation được ưa chuộng hơn vì nó ít invasive hơn và linh hoạt hơn.


[[jpa.auditing.configuration]]
== Cấu hình Auditing Tổng quát

Spring Data JPA đi kèm với một entity listener có thể được dùng để kích hoạt việc capture auditing information. Trước tiên, bạn phải đăng ký `AuditingEntityListener` để dùng cho tất cả entity trong persistence context của bạn bên trong file `orm.xml`, như ví dụ sau:

.Auditing configuration orm.xml
====
[source, xml]
----
<persistence-unit-metadata>
  <persistence-unit-defaults>
    <entity-listeners>
      <entity-listener class="….data.jpa.domain.support.AuditingEntityListener" />
    </entity-listeners>
  </persistence-unit-defaults>
</persistence-unit-metadata>
----
====

Bạn cũng có thể bật `AuditingEntityListener` theo từng entity riêng lẻ bằng cách dùng annotation `@EntityListeners`, như sau:

====
[source, java]
----
@Entity
@EntityListeners(AuditingEntityListener.class)
public class MyEntity {

}
----
====

NOTE: Tính năng auditing yêu cầu `spring-aspects.jar` phải có mặt trên classpath.

Sau khi `orm.xml` đã được chỉnh sửa phù hợp và `spring-aspects.jar` đã có trên classpath, việc kích hoạt chức năng auditing chỉ đơn giản là thêm element namespace `auditing` của Spring Data JPA vào configuration của bạn, như sau:

.Kích hoạt auditing bằng XML configuration
====
[source, xml]
----
<jpa:auditing auditor-aware-ref="yourAuditorAwareBean" />
----
====

Kể từ Spring Data JPA 1.5, bạn có thể bật auditing bằng cách đánh dấu một configuration class với annotation `@EnableJpaAuditing`. Bạn vẫn phải chỉnh sửa file `orm.xml` và có `spring-aspects.jar` trên classpath. Ví dụ sau minh họa cách dùng annotation `@EnableJpaAuditing`:

.Kích hoạt auditing bằng Java configuration
====
[source, java]
----
@Configuration
@EnableJpaAuditing
class Config {

  @Bean
  public AuditorAware<AuditableUser> auditorProvider() {
    return new AuditorAwareImpl();
  }
}
----
====

Nếu bạn expose một bean kiểu `AuditorAware` cho `ApplicationContext`, auditing infrastructure sẽ tự động nhận diện và sử dụng nó để xác định current user cần được set trên domain type. Nếu bạn có nhiều implementation được đăng ký trong `ApplicationContext`, bạn có thể chọn implementation nào sẽ được dùng bằng cách set tường minh attribute `auditorAwareRef` của `@EnableJpaAuditing`.

// FIXME: does this need to exist?
// [[jpa.misc]]
// = Miscellaneous Considerations

