[[core.extensions]]
= Extension của Spring Data

Phần này trình bày một tập các Spring Data extension giúp việc sử dụng Spring Data trở nên khả thi trong nhiều ngữ cảnh khác nhau.
Hiện tại, phần lớn các tích hợp này tập trung vào Spring MVC.

include::{commons}@data-commons::page$repositories/core-extensions-querydsl.adoc[leveloffset=1]

[[jpa.repositories.queries.type-safe.apt]]
=== Thiết lập Annotation Processing

Để sử dụng Querydsl với Spring Data JPA, bạn cần thiết lập annotation processing trong build system để sinh ra các class `Q`.
Mặc dù có thể tự viết các class `Q` bằng tay, nhưng nên dùng Querydsl annotation processor để sinh chúng tự động, giúp các class `Q` luôn đồng bộ với domain model của bạn.

Hầu hết người dùng Spring Data không sử dụng Querydsl, nên việc bắt buộc thêm dependency cho các project không được lợi từ Querydsl là không hợp lý.
Vì vậy, bạn cần tự kích hoạt annotation processing trong build system của mình.

Ví dụ sau minh họa cách thiết lập annotation processing thông qua các dependency và thay đổi cấu hình compiler trong Maven và Gradle:

[tabs]
======
Maven::
+
[source,xml,indent=0,subs="verbatim,quotes",role="primary"]
----
<dependencies>
    <dependency>
        <groupId>com.querydsl</groupId>
        <artifactId>querydsl-jpa</artifactId>
        <version>${querydslVersion}</version>
        <classifier>jakarta</classifier>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
                <annotationProcessorPaths>
                    <!-- Explicit opt-in required via annotationProcessors or
                        annotationProcessorPaths on Java 22+, see https://bugs.openjdk.org/browse/JDK-8306819 -->
                    <annotationProcessorPath>
                        <groupId>com.querydsl</groupId>
                        <artifactId>querydsl-apt</artifactId>
                        <version>${querydslVersion}</version>
                        <classifier>jakarta</classifier>
                    </annotationProcessorPath>
                    <annotationProcessorPath>
                        <groupId>jakarta.persistence</groupId>
                        <artifactId>jakarta.persistence-api</artifactId>
                    </annotationProcessorPath>
                </annotationProcessorPaths>

                <!-- Recommended: Some IDE's might require this configuration to include generated sources for IDE usage -->
                <generatedTestSourcesDirectory>target/generated-test-sources</generatedTestSourcesDirectory>
                <generatedSourcesDirectory>target/generated-sources</generatedSourcesDirectory>
            </configuration>
        </plugin>
    </plugins>
</build>
----

Gradle::
+
====
[source,groovy,indent=0,subs="verbatim,quotes",role="secondary"]
----
dependencies {

    implementation 'com.querydsl:querydsl-jpa:${querydslVersion}:jakarta'
    annotationProcessor 'com.querydsl:querydsl-apt:${querydslVersion}:jakarta'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

    testAnnotationProcessor 'com.querydsl:querydsl-apt:${querydslVersion}:jakarta'
    testAnnotationProcessor 'jakarta.persistence:jakarta.persistence-api'
}
----
====

Maven (OpenFeign)::
+
[source,xml,indent=0,subs="verbatim,quotes",role="primary"]
----
<dependencies>
    <dependency>
        <groupId>io.github.openfeign.querydsl</groupId>
        <artifactId>querydsl-jpa</artifactId>
        <version>${querydslVersion}</version>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
                <annotationProcessorPaths>
                    <!-- Explicit opt-in required via annotationProcessors or
                            annotationProcessorPaths on Java 22+, see https://bugs.openjdk.org/browse/JDK-8306819 -->
                    <annotationProcessorPath>
                        <groupId>io.github.openfeign.querydsl</groupId>
                        <artifactId>querydsl-apt</artifactId>
                        <version>${querydslVersion}</version>
                        <classifier>jpa</classifier>
                    </annotationProcessorPath>
                    <annotationProcessorPath>
                        <groupId>jakarta.persistence</groupId>
                        <artifactId>jakarta.persistence-api</artifactId>
                    </annotationProcessorPath>
                </annotationProcessorPaths>
                <!-- Recommended: Some IDE's might require this configuration to include generated sources for IDE usage -->
                <generatedTestSourcesDirectory>target/generated-test-sources</generatedTestSourcesDirectory>
                <generatedSourcesDirectory>target/generated-sources</generatedSourcesDirectory>
            </configuration>
        </plugin>
    </plugins>
</build>
----

Gradle (OpenFeign)::
+
====
[source,groovy,indent=0,subs="verbatim,quotes",role="secondary"]
----
dependencies {

    implementation "io.github.openfeign.querydsl:querydsl-jpa:${querydslVersion}"
    annotationProcessor "io.github.openfeign.querydsl:querydsl-apt:${querydslVersion}:jpa"
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

    testAnnotationProcessor "io.github.openfeign.querydsl:querydsl-apt:${querydslVersion}:jpa"
    testAnnotationProcessor 'jakarta.persistence:jakarta.persistence-api'
}
----
====
======

Lưu ý rằng phần thiết lập ở trên chỉ minh họa cách dùng đơn giản nhất, không đề cập đến các option hoặc dependency khác mà project của bạn có thể cần.

include::{commons}@data-commons::page$repositories/core-extensions-web.adoc[leveloffset=1]

include::{commons}@data-commons::page$repositories/core-extensions-populators.adoc[leveloffset=1]
