include::{commons}@data-commons-vi::page$repositories/custom-implementations.adoc[]

[[jpa.misc.jpa-context]]
== Sử dụng `JpaContext` trong Custom Implementation

Khi làm việc với nhiều instance `EntityManager` và xref:repositories/custom-implementations.adoc#repositories.custom-implementations[custom repository implementation], bạn cần wire đúng `EntityManager` vào repository implementation class. Bạn có thể làm điều này bằng cách đặt tên tường minh cho `EntityManager` trong annotation `@PersistenceContext`, hoặc nếu `EntityManager` được `@Autowired`, bằng cách dùng `@Qualifier`.

Từ Spring Data JPA 1.9, Spring Data JPA có một interface tên là `JpaContext` cho phép bạn lấy `EntityManager` theo managed domain class, với điều kiện domain class đó chỉ được quản lý bởi một trong các instance `EntityManager` trong ứng dụng. Ví dụ sau minh họa cách dùng `JpaContext` trong một custom repository:

.Sử dụng `JpaContext` trong một custom repository implementation
====
[source, java]
----
class UserRepositoryImpl implements UserRepositoryCustom {

  private final EntityManager em;

  @Autowired
  public UserRepositoryImpl(JpaContext context) {
    this.em = context.getEntityManagerByManagedType(User.class);
  }

  …
}
----
====

Ưu điểm của cách tiếp cận này là nếu domain type được gán sang một persistence unit khác, repository không cần phải sửa để thay đổi reference tới persistence unit.
