:support-qbe-collection: false
include::{commons}@data-commons::page$query-by-example.adoc[]

[[query-by-example.running]]
Trong Spring Data JPA, bạn có thể sử dụng Query by Example với Repository, như minh họa trong ví dụ sau:

.Query by Example sử dụng Repository
====
[source, java]
----
public interface PersonRepository extends JpaRepository<Person, String> { … }

public class PersonService {

  @Autowired PersonRepository personRepository;

  public List<Person> findPeople(Person probe) {
    return personRepository.findAll(Example.of(probe));
  }
}
----
====

Property specifier chấp nhận các property name (chẳng hạn `firstname` và `lastname`). Bạn có thể điều hướng bằng cách nối chuỗi các property lại với nhau qua dấu chấm (`address.city`). Bạn cũng có thể tinh chỉnh nó bằng matching option và case sensitivity.

Bảng sau cho thấy các option `StringMatcher` khác nhau mà bạn có thể sử dụng, cùng kết quả khi áp dụng chúng lên một field tên `firstname`:

[cols="1,2", options="header"]
.Các option của `StringMatcher`
|===
| Matching
| Kết quả logic

| `DEFAULT` (phân biệt hoa/thường)
| `firstname = ?0`

| `DEFAULT` (không phân biệt hoa/thường)
| `LOWER(firstname) = LOWER(?0)`

| `EXACT`  (phân biệt hoa/thường)
| `firstname = ?0`

| `EXACT` (không phân biệt hoa/thường)
| `LOWER(firstname) = LOWER(?0)`

| `STARTING`  (phân biệt hoa/thường)
| `firstname like ?0 + '%'`

| `STARTING` (không phân biệt hoa/thường)
| `LOWER(firstname) like LOWER(?0) + '%'`

| `ENDING`  (phân biệt hoa/thường)
| `firstname like '%' + ?0`

| `ENDING` (không phân biệt hoa/thường)
| `LOWER(firstname) like '%' + LOWER(?0)`

| `CONTAINING`  (phân biệt hoa/thường)
| `firstname like '%' + ?0 + '%'`

| `CONTAINING` (không phân biệt hoa/thường)
| `LOWER(firstname) like '%' + LOWER(?0) + '%'`

|===

NOTE: Regex-matching không được JPA hỗ trợ.
