include::{commons}@data-commons-vi::page$repositories/query-return-types-reference.adoc[]

[[return-type.stream]]
== Java `Stream`

Sử dụng Java `Stream` đòi hỏi phải cân nhắc thêm.
`Stream` ngụ ý việc thao tác trên một stateful resource gắn liền với các closeable resource (chẳng hạn như JDBC `ResultSet` hoặc `Statement`).
Các resource này thường gắn với chính stream và với transaction bao quanh nó.
Vì vậy, trả về `Stream<T>` yêu cầu phải có một transaction bao quanh để đảm bảo các resource luôn khả dụng đúng ngữ cảnh (điều này cũng áp dụng tương tự khi trả về JDBC `ResultSet`).

Hãy nhớ đóng `Stream` sau khi sử dụng, ví dụ:

====
[source,java]
----
@Transactional
public void processUsers() {
	try (Stream<User> users = repository.streamByFirstnameAndLastname("John", "Doe")) {
		// stream consumption
	}
}
----
====

Lưu ý rằng việc dùng `Stream<T>` không đảm bảo JPA provider hoặc JDBC driver của bạn sẽ fetch dữ liệu theo kiểu incremental (tăng dần).
Để xử lý result set lớn một cách tiết kiệm bộ nhớ, hãy dùng query hint để áp dụng cấu hình fetch-size đặc thù của provider, đồng thời kiểm tra tài liệu của JPA provider và JDBC driver để biết các giá trị và hành vi được hỗ trợ liên quan đến việc này.
Việc consume object từ `Stream` sẽ gắn các entity vào session cache, không khác gì so với bất kỳ collection type nào khác về mặt này.
