Hibernate dịch các lời gọi distance function thành các native database function cho PGvector và Oracle.
Kết quả của chúng thường là một distance.
Khi dùng `Similarity` thay vì `Score`, Spring Data chuẩn hóa các distance score thành một similarity score trong khoảng từ 0 đến 1. Score càng cao thì hai vector càng tương đồng.
// END

.Dùng `Score` và `Similarity` trong một Repository Search Method
====
[source,java]
----
interface CommentRepository extends Repository<Comment, String> {

  SearchResults<Comment> searchByEmbeddingNear(Vector vector, ScoringFunction function);

  SearchResults<Comment> searchByEmbeddingNear(Vector vector, Score score);

  SearchResults<Comment> searchByEmbeddingNear(Vector vector, Similarity similarity);

  SearchResults<Comment> searchByEmbeddingNear(Vector vector, Range<Similarity> range);
}

repository.searchByEmbeddingNear(Vector.of(…), ScoringFunction.cosine());                               <1>

repository.searchByEmbeddingNear(Vector.of(…), Score.of(0.9, ScoringFunction.cosine()));                <2>

repository.searchByEmbeddingNear(Vector.of(…), Similarity.of(0.9, ScoringFunction.cosine()));           <3>

repository.searchByEmbeddingNear(Vector.of(…), Similarity.between(0.5, 1, ScoringFunction.euclidean()));<4>
----

<1> Chạy một search và trả về các kết quả tương đồng với `Vector` đã cho, áp dụng Cosine scoring.
<2> Chạy một search và trả về các kết quả có score bằng hoặc nhỏ hơn `0.9`, dùng Cosine distance.
<3> Chạy một search và chuẩn hóa score thành một giá trị similarity.
Trả về các kết quả có similarity từ `0.9` trở lên, dùng Cosine scoring.
<4> Chạy một search và chuẩn hóa score thành một giá trị similarity.
Trả về các kết quả có similarity nằm trong khoảng từ `0.5` đến `1.0`, dùng Euclidean scoring.
====

NOTE: JPA yêu cầu phải cung cấp một `ScoringFunction` khi tạo instance `Score` hoặc `Similarity` để chọn một scoring function.
